#!/usr/bin/env sh

BAT=$(acpi -b | grep -E -o '1?[0-9][0-9]?%' | tr -d %)

# Set the icon and the color, based on status
if ! acpi -b | grep -q "Discharging"; then
    echo " $BAT"
    echo " $BAT"
elif [ $BAT -le 5 ]; then
    echo " $BAT"
    echo " $BAT"
    echo "#F2777A"
elif [ $BAT -le 20 ]; then
    echo " $BAT"
    echo " $BAT"
    echo "#FFCC66"
elif [ $BAT -le 50 ]; then
    echo " $BAT"
    echo " $BAT"
else
    echo " $BAT"
    echo " $BAT"
fi
