#!/usr/bin/sh

# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
if [ -z "$STEP" ] ; then
    STEP="${1:-5%}"
fi

active_sink=$(pactl info | grep "Default Sink" | cut -d":" -f2)
pactl_output=$(pactl list sinks | grep -A7 "Name:$active_sink")

volume=$(echo "$pactl_output" | grep -P "\tVolume:" | cut -d/ -f2 | tr -d " ")
muted=$(echo "$pactl_output" | grep Mute | cut -d" " -f2)

if [[ "$active_sink" =~ bluez_output.* ]]; then
    battery=$(bluetoothctl info | grep Battery | cut -d" " -f4)
    if [ "$muted" = yes ]; then
        echo " ($volume) $battery"
        echo " ($volume) $battery"
        echo "#F2777A"
    else
        echo " $volume $battery"
        echo " $volume $battery"
    fi
elif [ "$muted" = yes ]; then
    echo " ($volume)"
    echo " ($volume)"
    echo "#F2777A"
else
    echo " $volume"
    echo " $volume"
fi
