#!/usr/bin/sh

# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
if [[ -z "$STEP" ]] ; then
    STEP="${1:-5%}"
fi

pactl_output=$(pactl list sinks)

volume=$(echo "$pactl_output" | grep -A9 "State: RUNNING" | grep -P "\tVolume:" | cut -d/ -f2 | tr -d " ")
muted=$(echo "$pactl_output" | grep Mute | cut -d" " -f2)

if [ "$muted" = yes ]; then
    echo " ($volume)"
    echo " ($volume)"
    echo "#F2777A"
else
    echo " $volume"
    echo " $volume"
fi
