#!/usr/bin/sh

if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi

color_20_60=#FFAE00
color_low=#F2777A
color_down=#F2777A

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "down"
    echo "down"
    echo $color_down
    exit
fi

quality=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

echo $quality% # full text
echo $quality% # short text

# color
if [[ $quality -ge 60 ]]; then
    exit
elif [[ $quality -ge 20 ]]; then
    echo $color_20_60
else
    echo $color_low
fi
