# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt autocd
unsetopt beep
export KEYTIMEOUT=1
export TERM=xterm-256color # for tmux
bindkey -v # vim keybindings

# default editors
export EDITOR='vim'
export VEDITOR='code'

# load antibody
source <(antibody init)
antibody bundle < ~/.zsh/plugins.txt

source ~/.zsh/aliases.zsh
source ~/.zsh/colored-man.zsh

bindkey '^ ' autosuggest-accept

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/obabo/.zshrc'

autoload -Uz compinit
compinit
autoload -U promptinit; promptinit
prompt pure
# End of lines added by compinstall
#
export PATH=$PATH:~/.Scripts
