#!/bin/sh

[ "$(bluetooth)" != "bluetooth = on" ] && notify-send "Bluetooth is off" && exit 1

device="$(bluetoothctl devices Paired | cut -d\  -f2- | rofi -dmenu -i | awk '{print $1}')"
connected="$(bluetoothctl devices Connected | cut -d\  -f2)"

if [ "$device" = "$connected" ]; then
    bluetoothctl disconnect | while read output; do notify-send "$output"; done
else
    bluetoothctl connect "$device" | while read output; do notify-send "$output"; done
fi
