#!/usr/bin/env sh

if [ $# = 0 ]; then
    find $BOOKS -type f | cut -sd / -f 7-
else
    book=$(echo "${1}" | rev | cut -d / -f 1 | rev)
    i3-msg exec xdg-open $(find $BOOKS -type f -name "${book}") > /dev/null
fi
