#
# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# Prompt
PS1='> '

# Misc
shopt -s autocd
set -o vi

# Path
export PATH=$PATH:/home/obabo/.gem/ruby/2.5.0/bin
export PATH=$PATH:/home/obabo/.local/bin
export PATH=$PATH:/home/obabo/.Scripts/rofi
export PATH=$PATH:/home/obabo/.Scripts/util
export PATH=$PATH:/home/obabo/.npm/bin
export RANGER_LOAD_DEFAULT_RC=false 
export EDITOR=vim
