# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dcb1c586-c2c5-42b5-bb83-eb160e6a8f31";
      fsType = "ext4";
    };

  fileSystems."/mnt/Backup" =
    { device = "/dev/disk/by-uuid/8940d8bb-f9fb-447a-a399-e2704168ab4a";
      fsType = "ext4";
    };

  fileSystems."/home/obabo/Art" =
    { device = "/dev/disk/by-uuid/e77f33d0-d318-4ae4-ac4b-948dcfe0fd41";
      fsType = "ext4";
    };

  fileSystems."/mnt/Media" =
    { device = "/dev/disk/by-uuid/beaa72bd-4788-475e-9fab-22bcad9e63d1";
      fsType = "ext4";
    };


  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
